<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Square Impeller GPU render backend</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Square.Graphics\Square.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Square.Backends.Impeller.Tests" />
  </ItemGroup>

</Project>
