<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Square Controls + structural primitives</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Square.UI\Square.UI.csproj" />
    <ProjectReference Include="..\Square.Runtime\Square.Runtime.csproj" />
    <ProjectReference Include="..\Square.Graphics\Square.Graphics.csproj" />
    <ProjectReference Include="..\Square.Text\Square.Text.csproj" />
  </ItemGroup>

</Project>
