using System.Text;
using Square.SourceGenerator.Parser;

namespace Square.SourceGenerator.Emit
{
    internal sealed class ComponentEmitter
    {
        private readonly SqxDocument _doc;
        private readonly StringBuilder _sb = new StringBuilder();
        private int _showCounter;
        private int _forCounter;
        private int _showIndex;
        private int _forIndex;
        private int _varCounter;
        private readonly List<string> _refNames = new List<string>();

        public ComponentEmitter(SqxDocument doc) { _doc = doc; }

        public string Emit()
        {
            _showCounter = 0;
            _forCounter = 0;
            _showIndex = 0;
            _forIndex = 0;
            _varCounter = 0;

            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("#nullable enable");
            _sb.AppendLine();
            _sb.AppendLine("using Square.UI;");
            _sb.AppendLine("using Square.Runtime;");
            _sb.AppendLine("using Square.Runtime.Binding;");
            _sb.AppendLine("using Square.Graphics;");
            _sb.AppendLine("using Square.Controls.Controls;");
            _sb.AppendLine("using Square.Controls.Primitives;");
            _sb.AppendLine();
            _sb.AppendLine("namespace Square.Sample;");
            _sb.AppendLine();
            _sb.AppendLine("public partial class " + _doc.Name + " : UIElement");
            _sb.AppendLine("{");

            CollectRefs(_doc.Template.Roots);
            CountStructs(_doc.Template.Roots);
            EmitRefFields();
            EmitStructFields();

            _sb.AppendLine();
            _sb.AppendLine("    public override void BuildVisualTree()");
            _sb.AppendLine("    {");
            EmitNodes(_doc.Template.Roots, "        ");
            _sb.AppendLine("    }");

            EmitScript();
            EmitStyle();

            _sb.AppendLine("}");

            return _sb.ToString();
        }

        private void CollectRefs(List<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is SqxElement el)
                {
                    var refAttr = FindAttr(el, "ref");
                    if (refAttr != null && !string.IsNullOrEmpty(refAttr.RawValue))
                    {
                        if (!_refNames.Contains(refAttr.RawValue))
                            _refNames.Add(refAttr.RawValue);
                    }
                    CollectRefs(el.Children);
                }
            }
        }

        private void CountStructs(List<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is SqxElement el)
                {
                    if (el.Kind == SqxNodeKind.Show) _showCounter++;
                    if (el.Kind == SqxNodeKind.For) _forCounter++;
                    CountStructs(el.Children);
                }
            }
        }

        private void EmitRefFields()
        {
            foreach (var name in _refNames)
                _sb.AppendLine("    internal UIElement " + name + " = null!;");
            if (_refNames.Count > 0) _sb.AppendLine();
        }

        private void EmitStructFields()
        {
            for (int i = 0; i < _showCounter; i++)
                _sb.AppendLine("    private ShowNode _show" + i + " = null!;");
            for (int i = 0; i < _forCounter; i++)
                _sb.AppendLine("    private ForNode<object> _for" + i + " = null!;");
        }

        private void EmitNodes(List<SqxNode> nodes, string indent)
        {
            foreach (var node in nodes)
            {
                if (node is SqxText text)
                {
                    if (!string.IsNullOrEmpty(text.Text))
                        _sb.AppendLine(indent + "// Text: " + text.Text);
                }
                else if (node is SqxExpression expr)
                {
                    _sb.AppendLine(indent + "// Expression: " + expr.Expression);
                }
                else if (node is SqxElement el)
                {
                    EmitElement(el, indent);
                }
            }
        }

        private void EmitElement(SqxElement el, string indent)
        {
            if (el.Kind == SqxNodeKind.Show)
            {
                EmitShow(el, indent);
                return;
            }
            if (el.Kind == SqxNodeKind.For)
            {
                EmitFor(el, indent);
                return;
            }
            EmitControl(el, indent);
        }

        private void EmitControl(SqxElement el, string indent)
        {
            var refAttr = FindAttr(el, "ref");
            bool isRef = refAttr != null && !string.IsNullOrEmpty(refAttr.RawValue);
            var varName = isRef ? refAttr.RawValue : "_v" + (_varCounter++);
            var tagName = MapTagName(el.TagName);

            if (isRef)
                _sb.AppendLine(indent + varName + " = new " + tagName + "();");
            else
                _sb.AppendLine(indent + "var " + varName + " = new " + tagName + "();");

            foreach (var attr in el.Attributes)
            {
                if (attr.Name == "ref") continue;

                if (attr.Name == "class" && !attr.IsExpression)
                {
                    var classes = Split(attr.RawValue, ' ');
                    foreach (var cls in classes)
                        if (!string.IsNullOrEmpty(cls))
                            _sb.AppendLine(indent + varName + ".ClassList.Add(\"" + cls + "\");");
                    continue;
                }

                if (attr.Name == "style" && !attr.IsExpression)
                {
                    var decls = Split(attr.RawValue, ';');
                    foreach (var decl in decls)
                    {
                        var idx = decl.IndexOf(':');
                        if (idx > 0)
                        {
                            var prop = decl.Substring(0, idx).Trim();
                            var val = decl.Substring(idx + 1).Trim();
                            _sb.AppendLine(indent + varName + ".Style.Set(\"" + prop + "\", \"" + val + "\");");
                        }
                    }
                    continue;
                }

                if (attr.IsExpression)
                {
                    if (attr.Name.StartsWith("on"))
                    {
                        var eventName = attr.Name.Substring(2);
                        _sb.AppendLine(indent + varName + ".AddEventListener(\"" + eventName + "\", " + attr.RawValue + ");");
                    }
                    else
                    {
                        var propName = MapPropName(attr.Name);
                        _sb.AppendLine(indent + varName + ".BindProperty(\"" + propName + "\", () => " + attr.RawValue + ".Value);");
                    }
                }
                else
                {
                    var propName = MapPropName(attr.Name);
                    var val = attr.RawValue ?? "";
                    bool bv;
                    int iv;
                    if (bool.TryParse(val, out bv))
                        _sb.AppendLine(indent + varName + ".SetProperty(\"" + propName + "\", " + bv.ToString().ToLower() + ");");
                    else if (int.TryParse(val, out iv))
                        _sb.AppendLine(indent + varName + ".SetProperty(\"" + propName + "\", " + iv + ");");
                    else
                        _sb.AppendLine(indent + varName + ".SetProperty(\"" + propName + "\", \"" + val + "\");");
                }
            }

            if (el.Children.Count > 0)
            {
                _sb.AppendLine(indent + "{");
                EmitNodes(el.Children, indent + "    ");
                _sb.AppendLine(indent + "}");
            }

            _sb.AppendLine(indent + "Children.Add(" + varName + ");");
        }

        private void EmitShow(SqxElement el, string indent)
        {
            var idx = _showIndex++;     var when = FindAttr(el, "when");
            var condition = when != null ? when.RawValue : "false";

            _sb.AppendLine(indent + "_show" + idx + " = new ShowNode(() => " + condition + ".Value, () =>");
            _sb.AppendLine(indent + "{");
            EmitNodes(el.Children, indent + "    ");
            _sb.AppendLine(indent + "    return null;");
            _sb.AppendLine(indent + "});");
        }

        private void EmitFor(SqxElement el, string indent)
        {
            var idx = _forIndex++;
            var each = FindAttr(el, "each");
            var source = each != null ? each.RawValue : "Items";

            _sb.AppendLine(indent + "_for" + idx + " = new ForNode<object>(() => " + source + ", (it) =>");
            _sb.AppendLine(indent + "{");
            EmitNodes(el.Children, indent + "    ");
            _sb.AppendLine(indent + "    return null;");
            _sb.AppendLine(indent + "});");
        }

        private void EmitScript()
        {
            if (!string.IsNullOrEmpty(_doc.ScriptCode))
            {
                _sb.AppendLine();
                _sb.AppendLine("    #region Script");
                var lines = _doc.ScriptCode.Split('\n');
                foreach (var line in lines)
                    _sb.AppendLine("    " + line.TrimEnd());
                _sb.AppendLine("    #endregion");
            }
        }

        private void EmitStyle()
        {
            if (!string.IsNullOrEmpty(_doc.StyleCode))
            {
                _sb.AppendLine();
                _sb.AppendLine("    /* Style: " + _doc.StyleCode + " */");
            }
        }

        private static SqxAttribute FindAttr(SqxElement el, string name)
        {
            foreach (var a in el.Attributes)
                if (a.Name == name) return a;
            return null;
        }

        private static string[] Split(string s, char sep)
        {
            if (s == null) return new string[0];
            return s.Split(sep);
        }

        private static string MapTagName(string tag)
        {
            if (tag == "Text") return "Square.Controls.Controls.Text";
            if (tag == "Image") return "Square.Controls.Controls.Image";
            return tag;
        }

        private static string MapPropName(string name)
        {
            if (name == "text") return "TextContent";
            if (name == "value") return "Value";
            if (name == "checked") return "IsChecked";
            if (name == "disabled") return "IsEnabled";
            if (name == "color") return "Color";
            if (name == "background") return "Background";
            return name;
        }
    }
}