using System.Text;
using Square.SourceGenerator.Parser;

namespace Square.SourceGenerator.Emit
{
    internal sealed class ComponentEmitter
    {
        private readonly SqxDocument _doc;
        private readonly string _namespace;
        private readonly StringBuilder _sb = new StringBuilder();
        private readonly List<RefInfo> _refs = new List<RefInfo>();
        private int _showCounter;
        private int _forCounter;
        private int _showIndex;
        private int _forIndex;
        private int _varCounter;
        private int _slotCounter;

        public ComponentEmitter(SqxDocument doc, string namespaceName = "Square.Sample")
        {
            _doc = doc;
            _namespace = !string.IsNullOrWhiteSpace(doc.Namespace)
                ? doc.Namespace
                : string.IsNullOrWhiteSpace(namespaceName) ? "Square.Sample" : namespaceName;
        }

        public string Emit()
        {
            ResetState();
            CollectRefs(_doc.Template.Roots);
            CountStructs(_doc.Template.Roots);

            _sb.AppendLine("// <auto-generated/>");
            _sb.AppendLine("#nullable enable");
            _sb.AppendLine();
            _sb.AppendLine("using Square.UI;");
            _sb.AppendLine("using Square.Events;");
            _sb.AppendLine("using Square.Runtime;");
            _sb.AppendLine("using Square.Runtime.Binding;");
            _sb.AppendLine("using Square.Graphics;");
            _sb.AppendLine("using Square.Controls.Controls;");
            _sb.AppendLine("using Square.Controls.Primitives;");
            _sb.AppendLine();
            _sb.AppendLine("namespace " + _namespace + ";");
            _sb.AppendLine();
            _sb.AppendLine(_doc.Access + " partial class " + _doc.Name + " : UIElement");
            _sb.AppendLine("{");

            EmitFields();
            _sb.AppendLine("    public override void BuildVisualTree()");
            _sb.AppendLine("    {");
            _sb.AppendLine("        if (_visualTreeBuilt) return;");
            _sb.AppendLine("        _visualTreeBuilt = true;");
            EmitNodes(_doc.Template.Roots, "        ", "this", null);
            if (!string.IsNullOrWhiteSpace(_doc.StyleCode))
                _sb.AppendLine("        ApplyComponentStyles(this);");
            _sb.AppendLine("    }");

            EmitScript();
            EmitStyleSupport();
            _sb.AppendLine("}");
            return _sb.ToString();
        }

        private void ResetState()
        {
            _showCounter = 0;
            _forCounter = 0;
            _showIndex = 0;
            _forIndex = 0;
            _varCounter = 0;
            _slotCounter = 0;
            _refs.Clear();
            _sb.Clear();
        }

        private void CollectRefs(List<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is not SqxElement element) continue;
                var refAttr = FindAttr(element, "ref");
                if (refAttr != null && !string.IsNullOrWhiteSpace(refAttr.RawValue) &&
                    !_refs.Exists(item => item.Name == refAttr.RawValue))
                {
                    _refs.Add(new RefInfo(refAttr.RawValue, MapTagName(element.TagName)));
                }
                CollectRefs(element.Children);
            }
        }

        private void CountStructs(List<SqxNode> nodes)
        {
            foreach (var node in nodes)
            {
                if (node is not SqxElement element) continue;
                if (element.Kind == SqxNodeKind.Show) _showCounter++;
                if (element.Kind == SqxNodeKind.For) _forCounter++;
                CountStructs(element.Children);
            }
        }

        private void EmitFields()
        {
            _sb.AppendLine("    private bool _visualTreeBuilt;");
            foreach (var item in _refs)
                _sb.AppendLine("    internal " + item.TypeName + " " + item.Name + " = null!;");
            for (var i = 0; i < _showCounter; i++)
                _sb.AppendLine("    private ShowNode _show" + i + " = null!;");
            for (var i = 0; i < _forCounter; i++)
                _sb.AppendLine("    private IForNode _for" + i + " = null!;");
            _sb.AppendLine();

            if ((_refs.Count > 0 || _showCounter > 0 || _forCounter > 0) &&
                !ContainsOnDetachedCore(_doc.ScriptCode))
            {
                _sb.AppendLine("    protected override void OnDetachedCore()");
                _sb.AppendLine("    {");
                foreach (var item in _refs)
                    _sb.AppendLine("        " + item.Name + " = null!;");
                for (var i = 0; i < _showCounter; i++)
                    _sb.AppendLine("        _show" + i + " = null!;");
                for (var i = 0; i < _forCounter; i++)
                    _sb.AppendLine("        _for" + i + " = null!;");
                _sb.AppendLine("        base.OnDetachedCore();");
                _sb.AppendLine("    }");
                _sb.AppendLine();
            }
        }

        private void EmitNodes(List<SqxNode> nodes, string indent, string parentName, string localName)
        {
            foreach (var node in nodes)
            {
                if (IsWrapperExpression(node)) continue;

                if (node is SqxText text)
                {
                    if (string.IsNullOrWhiteSpace(text.Text)) continue;
                    var textName = EmitText(text.Text, indent);
                    _sb.AppendLine(indent + parentName + ".Children.Add(" + textName + ");");
                }
                else if (node is SqxExpression expression)
                {
                    var textName = EmitExpressionText(expression.Expression, indent, localName);
                    _sb.AppendLine(indent + parentName + ".Children.Add(" + textName + ");");
                }
                else if (node is SqxElement element)
                {
                    if (element.Kind == SqxNodeKind.Show)
                        EmitShow(element, indent, parentName, localName);
                    else if (element.Kind == SqxNodeKind.For)
                        EmitFor(element, indent, parentName);
                    else if (element.Kind == SqxNodeKind.Slot)
                        EmitSlot(element, indent, parentName, localName);
                    else if (element.Kind == SqxNodeKind.Router)
                    {
                        var routerName = EmitRouter(element, indent, localName);
                        _sb.AppendLine(indent + parentName + ".Children.Add(" + routerName + ");");
                    }
                    else if (element.Kind == SqxNodeKind.Route)
                        continue;
                    else
                    {
                        var elementName = EmitControl(element, indent, localName);
                        _sb.AppendLine(indent + parentName + ".Children.Add(" + elementName + ");");
                    }
                }
            }
        }

        private string EmitControl(SqxElement element, string indent, string localName)
        {
            var refAttr = FindAttr(element, "ref");
            var isRef = refAttr != null && !string.IsNullOrWhiteSpace(refAttr.RawValue);
            var variableName = isRef ? refAttr.RawValue : NextVariable();
            var tagName = MapTagName(element.TagName);
            var isCustomComponent = !IsBuiltInTag(element.TagName);

            if (isRef)
                _sb.AppendLine(indent + variableName + " = new " + tagName + "();");
            else
                _sb.AppendLine(indent + "var " + variableName + " = new " + tagName + "();");

            foreach (var attribute in element.Attributes)
                EmitAttribute(variableName, attribute, indent, localName);

            if (isCustomComponent)
            {
                EmitComponentSlots(element, variableName, indent, localName);
                _sb.AppendLine(indent + variableName + ".BuildVisualTree();");
            }
            else if (!EmitTextContent(element, variableName, indent, localName))
                EmitNodes(element.Children, indent, variableName, localName);

            return variableName;
        }

        private void EmitAttribute(string variableName, SqxAttribute attribute, string indent, string localName)
        {
            if (attribute.Name == "ref" || attribute.Name == "slot") return;

            if (attribute.Name == "class" && !attribute.IsExpression)
            {
                foreach (var className in Split(attribute.RawValue, ' '))
                    if (!string.IsNullOrWhiteSpace(className))
                        _sb.AppendLine(indent + variableName + ".ClassList.Add(\"" + Escape(className) + "\");");
                return;
            }

            if (attribute.Name == "style" && !attribute.IsExpression)
            {
                foreach (var declaration in Split(attribute.RawValue, ';'))
                {
                    var separator = declaration.IndexOf(':');
                    if (separator <= 0) continue;
                    var property = declaration.Substring(0, separator).Trim();
                    var value = declaration.Substring(separator + 1).Trim();
                    _sb.AppendLine(indent + variableName + ".Style.Set(\"" + Escape(property) + "\", \"" + Escape(value) + "\");");
                }
                return;
            }

            if (attribute.IsExpression)
            {
                if (attribute.Name.StartsWith("on", StringComparison.OrdinalIgnoreCase))
                {
                    var eventName = attribute.Name.Substring(2).ToLowerInvariant();
                    _sb.AppendLine(indent + variableName + ".AddEventListener(\"" + eventName + "\", " + attribute.RawValue + ");");
                }
                else
                {
                    var propertyName = MapPropName(attribute.Name);
                    if (IsLocalExpression(attribute.RawValue, localName))
                        _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propertyName + "\", " + attribute.RawValue + ");");
                    else
                        _sb.AppendLine(indent + variableName + ".BindProperty(\"" + propertyName + "\", " + attribute.RawValue + ");");
                }
                return;
            }

            var propName = MapPropName(attribute.Name);
            var rawValue = attribute.RawValue ?? "";
            if (attribute.Name.Equals("disabled", StringComparison.OrdinalIgnoreCase) && string.IsNullOrEmpty(rawValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", true);");
            else if (bool.TryParse(rawValue, out var boolValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", " + boolValue.ToString().ToLowerInvariant() + ");");
            else if (int.TryParse(rawValue, out var intValue))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", " + intValue + ");");
            else
                _sb.AppendLine(indent + variableName + ".SetProperty(\"" + propName + "\", \"" + Escape(rawValue) + "\");");
        }

        private bool EmitTextContent(SqxElement element, string variableName, string indent, string localName)
        {
            if (element.TagName != "Text" && element.TagName != "Button" && element.TagName != "Link") return false;
            if (FindAttr(element, "text") != null) return true;

            var content = element.Children.Where(node => !IsWrapperExpression(node)).ToList();
            if (content.Count == 0) return true;
            if (content.All(node => node is SqxText))
            {
                var value = string.Concat(content.Cast<SqxText>().Select(node => node.Text));
                _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", \"" + Escape(value.Trim()) + "\");");
                return true;
            }
            if (content.Count == 1 && content[0] is SqxExpression expression)
            {
                if (IsLocalExpression(expression.Expression, localName))
                    _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", (" + expression.Expression + ")?.ToString() ?? \"\");");
                else
                    _sb.AppendLine(indent + variableName + ".BindProperty(\"TextContent\", " + expression.Expression + ");");
                return true;
            }
            return false;
        }

        private void EmitShow(SqxElement element, string indent, string parentName, string localName)
        {
            var index = _showIndex++;
            var condition = FindAttr(element, "when")?.RawValue ?? "new ObservableValue<bool>(false)";
            _sb.AppendLine(indent + "_show" + index + " = new ShowNode(" + condition + ", () =>");
            _sb.AppendLine(indent + "{");
            EmitFactoryBody(element.Children, indent + "    ", localName);
            _sb.AppendLine(indent + "});");
            _sb.AppendLine(indent + "_show" + index + ".AttachTo(" + parentName + ");");
        }

        private void EmitFor(SqxElement element, string indent, string parentName)
        {
            var index = _forIndex++;
            var source = FindAttr(element, "each")?.RawValue ?? "System.Array.Empty<object>()";
            _sb.AppendLine(indent + "_for" + index + " = ForNode.Create(" + source + ", it =>");
            _sb.AppendLine(indent + "{");
            EmitFactoryBody(element.Children, indent + "    ", "it");
            _sb.AppendLine(indent + "});");
            _sb.AppendLine(indent + "_for" + index + ".AttachTo(" + parentName + ");");
        }

        private void EmitSlot(SqxElement element, string indent, string parentName, string localName)
        {
            var name = FindAttr(element, "name")?.RawValue ?? "";
            _sb.AppendLine(indent + "if (!Slots.Render(\"" + Escape(name) + "\", " + parentName + "))");
            _sb.AppendLine(indent + "{");
            EmitNodes(element.Children, indent + "    ", parentName, localName);
            _sb.AppendLine(indent + "}");
        }

        private void EmitComponentSlots(SqxElement element, string variableName, string indent, string localName)
        {
            var groups = new List<KeyValuePair<string, List<SqxNode>>>();
            foreach (var child in element.Children)
            {
                if (IsWrapperExpression(child)) continue;
                var slotName = "";
                if (child is SqxElement childElement)
                    slotName = FindAttr(childElement, "slot")?.RawValue ?? "";

                var groupIndex = groups.FindIndex(pair => pair.Key == slotName);
                if (groupIndex < 0)
                {
                    groups.Add(new KeyValuePair<string, List<SqxNode>>(slotName, new List<SqxNode> { child }));
                }
                else
                {
                    groups[groupIndex].Value.Add(child);
                }
            }

            foreach (var group in groups)
            {
                var parentParameter = "__slotParent" + _slotCounter++;
                _sb.AppendLine(indent + variableName + ".Slots.Set(\"" + Escape(group.Key) + "\", " + parentParameter + " =>");
                _sb.AppendLine(indent + "{");
                EmitNodes(group.Value, indent + "    ", parentParameter, localName);
                _sb.AppendLine(indent + "});");
            }
        }

        private string EmitRouter(SqxElement element, string indent, string localName)
        {
            var refAttr = FindAttr(element, "ref");
            var isRef = refAttr != null && !string.IsNullOrWhiteSpace(refAttr.RawValue);
            var variableName = isRef ? refAttr.RawValue : NextVariable();
            if (isRef)
                _sb.AppendLine(indent + variableName + " = new Square.Router.Router();");
            else
                _sb.AppendLine(indent + "var " + variableName + " = new Square.Router.Router();");

            var initialPath = FindAttr(element, "initialPath");
            if (initialPath != null)
            {
                if (initialPath.IsExpression)
                    _sb.AppendLine(indent + variableName + ".InitialPath = " + initialPath.RawValue + ";");
                else
                    _sb.AppendLine(indent + variableName + ".InitialPath = \"" + Escape(initialPath.RawValue ?? "/") + "\";");
            }

            foreach (var attribute in element.Attributes)
            {
                if (attribute.Name == "initialPath" || attribute.Name == "ref") continue;
                EmitAttribute(variableName, attribute, indent, localName);
            }

            foreach (var route in element.Children.OfType<SqxElement>().Where(child => child.Kind == SqxNodeKind.Route))
            {
                var routeName = EmitRouteDefinition(route, indent);
                _sb.AppendLine(indent + variableName + ".Routes.Add(" + routeName + ");");
            }

            _sb.AppendLine(indent + variableName + ".Start();");
            return variableName;
        }

        private string EmitRouteDefinition(SqxElement element, string indent)
        {
            var variableName = NextVariable();
            var path = FindAttr(element, "path")?.RawValue ?? "/";
            var component = FindAttr(element, "component")?.RawValue;
            var factory = string.IsNullOrWhiteSpace(component) ? "null" : "() => new " + component + "()";
            _sb.AppendLine(indent + "var " + variableName + " = new Square.Router.RouteDefinition(\"" + Escape(path) + "\", " + factory + ");");

            foreach (var child in element.Children.OfType<SqxElement>().Where(node => node.Kind == SqxNodeKind.Route))
            {
                var childName = EmitRouteDefinition(child, indent);
                _sb.AppendLine(indent + variableName + ".Children.Add(" + childName + ");");
            }

            return variableName;
        }

        private void EmitFactoryBody(List<SqxNode> nodes, string indent, string localName)
        {
            var content = nodes.Where(node => !IsWrapperExpression(node)).ToList();
            if (content.Count == 0)
            {
                _sb.AppendLine(indent + "return null;");
                return;
            }

            if (content.Count == 1)
            {
                var rootName = EmitFactoryRoot(content[0], indent, localName);
                if (!string.IsNullOrWhiteSpace(_doc.StyleCode))
                    _sb.AppendLine(indent + "ApplyComponentStyles(" + rootName + ");");
                _sb.AppendLine(indent + "return " + rootName + ";");
                return;
            }

            var fragmentName = NextVariable();
            _sb.AppendLine(indent + "var " + fragmentName + " = new View();");
            EmitNodes(content, indent, fragmentName, localName);
            if (!string.IsNullOrWhiteSpace(_doc.StyleCode))
                _sb.AppendLine(indent + "ApplyComponentStyles(" + fragmentName + ");");
            _sb.AppendLine(indent + "return " + fragmentName + ";");
        }

        private string EmitFactoryRoot(SqxNode node, string indent, string localName)
        {
            if (node is SqxElement element && element.Kind == SqxNodeKind.Element)
                return EmitControl(element, indent, localName);
            if (node is SqxText text)
                return EmitText(text.Text, indent);
            if (node is SqxExpression expression)
                return EmitExpressionText(expression.Expression, indent, localName);

            var fallback = NextVariable();
            _sb.AppendLine(indent + "var " + fallback + " = new View();");
            return fallback;
        }

        private string EmitText(string value, string indent)
        {
            var variableName = NextVariable();
            _sb.AppendLine(indent + "var " + variableName + " = new Square.Controls.Controls.Text(\"" + Escape(value.Trim()) + "\");");
            return variableName;
        }

        private string EmitExpressionText(string expression, string indent, string localName)
        {
            var variableName = NextVariable();
            _sb.AppendLine(indent + "var " + variableName + " = new Square.Controls.Controls.Text();");
            if (IsLocalExpression(expression, localName))
                _sb.AppendLine(indent + variableName + ".SetProperty(\"TextContent\", (" + expression + ")?.ToString() ?? \"\");");
            else
                _sb.AppendLine(indent + variableName + ".BindProperty(\"TextContent\", " + expression + ");");
            return variableName;
        }

        private void EmitScript()
        {
            if (string.IsNullOrWhiteSpace(_doc.ScriptCode)) return;
            _sb.AppendLine();
            _sb.AppendLine("    #region Script");
            foreach (var line in _doc.ScriptCode.Split('\n'))
                _sb.AppendLine("    " + line.TrimEnd('\r'));
            _sb.AppendLine("    #endregion");
        }

        private void EmitStyleSupport()
        {
            if (string.IsNullOrWhiteSpace(_doc.StyleCode)) return;
            var css = _doc.StyleCode.Replace("\"", "\"\"");
            _sb.AppendLine();
            _sb.AppendLine("    private static readonly Square.CSS.Ast.CssStyleSheet ComponentStyleSheet =");
            _sb.AppendLine("        new Square.CSS.Engine.CssParser(new Square.CSS.Tokenizer.CssTokenizer(@\"" + css + "\").Tokenize()).Parse();");
            _sb.AppendLine();
            _sb.AppendLine("    private static void ApplyComponentStyles(Visual root)");
            _sb.AppendLine("    {");
            _sb.AppendLine("        var engine = new Square.CSS.Engine.CssEngine();");
            _sb.AppendLine("        engine.LoadStyleSheet(ComponentStyleSheet);");
            _sb.AppendLine("        engine.ApplyStylesToTree(root);");
            _sb.AppendLine("    }");
        }

        private string NextVariable() => "_v" + _varCounter++;

        private static bool IsLocalExpression(string expression, string localName)
        {
            if (string.IsNullOrWhiteSpace(localName) || string.IsNullOrWhiteSpace(expression)) return false;
            var value = expression.Trim();
            return value == localName || value.StartsWith(localName + ".", StringComparison.Ordinal) ||
                   value.StartsWith(localName + "[", StringComparison.Ordinal);
        }

        private static bool ContainsOnDetachedCore(string script) =>
            !string.IsNullOrEmpty(script) &&
            script.Contains("OnDetachedCore", StringComparison.Ordinal);

        private static bool IsWrapperExpression(SqxNode node)
        {
            if (node is not SqxExpression expression) return false;
            var value = expression.Expression.Trim();
            return value.EndsWith("=>", StringComparison.Ordinal) || value == "}";
        }

        private static SqxAttribute FindAttr(SqxElement element, string name) =>
            element.Attributes.FirstOrDefault(attribute => string.Equals(attribute.Name, name, StringComparison.OrdinalIgnoreCase));

        private static string[] Split(string value, char separator) =>
            value == null ? Array.Empty<string>() : value.Split(separator);

        private static string Escape(string value) =>
            value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "\\r").Replace("\n", "\\n");

        private static string MapTagName(string tag) => tag switch
        {
            "View" => "Square.Controls.Controls.View",
            "Text" => "Square.Controls.Controls.Text",
            "Button" => "Square.Controls.Controls.Button",
            "Input" => "Square.Controls.Controls.Input",
            "TextArea" => "Square.Controls.Controls.TextArea",
            "CheckBox" => "Square.Controls.Controls.CheckBox",
            "Radio" => "Square.Controls.Controls.Radio",
            "Select" => "Square.Controls.Controls.Select",
            "Image" => "Square.Controls.Controls.Image",
            "Canvas" => "Square.Controls.Controls.Canvas",
            "Link" => "Square.Router.Link",
            "Router" => "Square.Router.Router",
            _ => tag
        };

        private static bool IsBuiltInTag(string tag) => tag == "View" || tag == "Text" || tag == "Button" ||
            tag == "Input" || tag == "TextArea" || tag == "CheckBox" || tag == "Radio" || tag == "Select" ||
            tag == "Image" || tag == "Canvas" || tag == "Link";

        private static string MapPropName(string name) => name switch
        {
            "text" => "TextContent",
            "value" => "Value",
            "checked" => "IsChecked",
            "disabled" => "IsDisabled",
            "placeholder" => "Placeholder",
            "source" => "Source",
            "image" => "ImageContent",
            "group" => "GroupName",
            "options" => "Options",
            "to" => "To",
            "replace" => "Replace",
            "color" => "Color",
            "background" => "Background",
            _ => name
        };

        private sealed class RefInfo
        {
            public string Name { get; }
            public string TypeName { get; }

            public RefInfo(string name, string typeName)
            {
                Name = name;
                TypeName = typeName;
            }
        }
    }
}
