<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(IsWindowsBuild)' != 'false'">WinExe</OutputType>
    <OutputType Condition="'$(IsWindowsBuild)' == 'false'">Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Description>Square Sample Application</Description>
    <PublishAot Condition="'$(SquareSamplePublishAot)' == 'true'">true</PublishAot>
    <SquareSampleUseVulkan Condition="'$(SquareSampleUseVulkan)' == '' and '$(SquareSamplePublishAot)' != 'true'">true</SquareSampleUseVulkan>
    <SquareSampleUseVulkan Condition="'$(SquareSampleUseVulkan)' == ''">false</SquareSampleUseVulkan>
    <SquareSampleUseTooling Condition="'$(SquareSampleUseTooling)' == '' and '$(SquareSamplePublishAot)' != 'true'">true</SquareSampleUseTooling>
    <SquareSampleUseTooling Condition="'$(SquareSampleUseTooling)' == ''">false</SquareSampleUseTooling>
    <EmitCompilerGeneratedFiles Condition="'$(SquareEmitCompilerGeneratedFiles)' == 'true'">true</EmitCompilerGeneratedFiles>
    <OptimizationPreference>Size</OptimizationPreference>
    <DefineConstants Condition="'$(SquareSampleUseVulkan)' == 'true'">$(DefineConstants);SQUARE_SAMPLE_VULKAN</DefineConstants>
    <DefineConstants Condition="'$(SquareSampleUseTooling)' == 'true'">$(DefineConstants);SQUARE_SAMPLE_TOOLING</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Square\Square.csproj" />
    <ProjectReference Include="..\..\src\Square.Platform.Win32\Square.Platform.Win32.csproj" Condition="'$(SquareTargetPlatform)' == 'Win32'" />
    <ProjectReference Include="..\..\src\Square.Platform.X11\Square.Platform.X11.csproj" Condition="'$(SquareTargetPlatform)' == 'X11'" />
    <ProjectReference Include="..\..\src\Square.Backends.Vulkan\Square.Backends.Vulkan.csproj" Condition="'$(SquareSampleUseVulkan)' == 'true'" />
    <ProjectReference Include="..\..\src\Square.Tooling\Square.Tooling.csproj" Condition="'$(SquareSampleUseTooling)' == 'true'" />
    <ProjectReference Include="..\..\src\Square.Compiler\Square.Compiler.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="**\*.sqx" />
  </ItemGroup>

</Project>
