<Project Sdk="Microsoft.NET.Sdk" TreatAsLocalProperty="PublishAot">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <Description>Square markup compiler and Roslyn source generator</Description>
    <LangVersion>latest</LangVersion>
    <PublishAot>false</PublishAot>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);RS1035;RS2008</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <Nullable>annotations</Nullable>
    <NoWarn>$(NoWarn);RS1035;RS2008;RS1041;RS1036</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <Compile Remove="Markup\**\*.cs" />
  </ItemGroup>

</Project>
