<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Square desktop UI framework</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StbTrueTypeSharp" />
    <PackageReference Include="Yoga.Net" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Square.Backends.Tests" />
    <InternalsVisibleTo Include="Square.Images.Tests" />
    <InternalsVisibleTo Include="Square.UI.Tests" />
  </ItemGroup>

</Project>
