<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Square Layout Engine</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Square.UI\Square.UI.csproj" />
    <ProjectReference Include="..\Square.Graphics\Square.Graphics.csproj" />
  </ItemGroup>

</Project>