<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(IsWindowsBuild)' != 'false'">WinExe</OutputType>
    <OutputType Condition="'$(IsWindowsBuild)' == 'false'">Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Description>Square RichText Editor Demo</Description>
    <PublishAot>true</PublishAot>
    <EmitCompilerGeneratedFiles Condition="'$(SquareEmitCompilerGeneratedFiles)' == 'true'">true</EmitCompilerGeneratedFiles>
    <OptimizationPreference>Size</OptimizationPreference>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Square\Square.csproj" />
    <ProjectReference Include="..\..\src\Square.Platform.Win32\Square.Platform.Win32.csproj" Condition="'$(SquareTargetPlatform)' == 'Win32'" />
    <ProjectReference Include="..\..\src\Square.Platform.X11\Square.Platform.X11.csproj" Condition="'$(SquareTargetPlatform)' == 'X11'" />
    <ProjectReference Include="..\..\src\Square.Extensions\Square.Extensions.csproj" />
    <ProjectReference Include="..\..\src\Square.Tooling\Square.Tooling.csproj" />
    <ProjectReference Include="..\..\src\Square.Compiler\Square.Compiler.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="**\*.sqx" />
  </ItemGroup>

</Project>
