<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(IsWindowsBuild)' != 'false'">WinExe</OutputType>
    <OutputType Condition="'$(IsWindowsBuild)' == 'false'">Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Description>Square Impeller Vulkan smoke sample</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Square.Backends.Impeller\Square.Backends.Impeller.csproj" />
    <ProjectReference Include="..\..\src\Square.Graphics\Square.Graphics.csproj" />
    <ProjectReference Include="..\..\src\Square.Hosting\Square.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Square.Platform\Square.Platform.csproj" />
    <ProjectReference Include="..\..\src\Square.UI\Square.UI.csproj" />
  </ItemGroup>

</Project>
