<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Square Platform: host abstraction</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <IsWindowsBuild Condition="'$(OS)' == 'Windows_NT'">true</IsWindowsBuild>
    <IsWindowsBuild Condition="'$(RuntimeIdentifier)' != '' and $(RuntimeIdentifier.Contains('linux'))">false</IsWindowsBuild>
    <IsWindowsBuild Condition="'$(RuntimeIdentifier)' != '' and $(RuntimeIdentifier.Contains('osx'))">false</IsWindowsBuild>
    <IsWindowsBuild Condition="'$(IsWindowsBuild)' == ''">false</IsWindowsBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Square.Graphics\Square.Graphics.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsWindowsBuild)' == 'true'">
    <Compile Remove="X11\**" />
  </ItemGroup>

  <ItemGroup Condition="'$(IsWindowsBuild)' != 'true'">
    <Compile Remove="Win32\**" />
  </ItemGroup>

</Project>
