using System.Text;
using Silk.NET.Shaderc;

// Compiles the GLSL shaders in src/Square.Backends.Vulkan/Shaders/ to SPIR-V
// and regenerates src/Square.Backends.Vulkan/EmbeddedShaders.cs.
//
// Usage: dotnet run --project tools/ShaderGen

unsafe class Program
{
    static int Main()
    {
        var repoRoot = FindRepoRoot();
        var shaderDir = Path.Combine(repoRoot, "src", "Square.Backends.Vulkan", "Shaders");
        var outputPath = Path.Combine(repoRoot, "src", "Square.Backends.Vulkan", "EmbeddedShaders.cs");

        var vertSource = File.ReadAllText(Path.Combine(shaderDir, "vert2d.glsl"));
        var fragSource = File.ReadAllText(Path.Combine(shaderDir, "frag2d.glsl"));

        var api = Shaderc.GetApi();
        var compiler = api.CompilerInitialize();
        if (compiler == null)
        {
            Console.Error.WriteLine("Failed to initialize shaderc compiler.");
            return 1;
        }

        var options = api.CompileOptionsInitialize();
        try
        {
            var vertSpv = Compile(api, compiler, options, vertSource, ShaderKind.VertexShader, "vert2d.glsl");
            var fragSpv = Compile(api, compiler, options, fragSource, ShaderKind.FragmentShader, "frag2d.glsl");

            var sb = new StringBuilder();
            sb.AppendLine("namespace Square.Backends.Vulkan;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Embedded SPIR-V bytecode for the 2D batch rendering shaders.");
            sb.AppendLine("/// AUTO-GENERATED by tools/ShaderGen from Shaders/*.glsl - do not edit by hand.");
            sb.AppendLine("/// Regenerate with: dotnet run --project tools/ShaderGen");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("internal static class EmbeddedShaders");
            sb.AppendLine("{");
            AppendByteArray(sb, "Vertex2D", vertSpv);
            sb.AppendLine();
            AppendByteArray(sb, "Fragment2D", fragSpv);
            sb.AppendLine("}");

            File.WriteAllText(outputPath, sb.ToString());
            Console.WriteLine($"Wrote {outputPath}");
            Console.WriteLine($"  Vertex2D:   {vertSpv.Length} bytes");
            Console.WriteLine($"  Fragment2D: {fragSpv.Length} bytes");
            return 0;
        }
        finally
        {
            api.CompileOptionsRelease(options);
            api.CompilerRelease(compiler);
        }
    }

    static byte[] Compile(Shaderc api, Compiler* compiler, CompileOptions* options, string source, ShaderKind kind, string fileName)
    {
        var byteCount = (nuint)Encoding.UTF8.GetByteCount(source);
        var result = api.CompileIntoSpv(compiler, source, byteCount, kind, fileName, "main", options);
        if (result == null)
            throw new Exception($"shaderc returned null for {fileName}.");

        var status = (int)api.ResultGetCompilationStatus(result);
        if (status != 0) // 0 == success
        {
            var err = api.ResultGetErrorMessageS(result);
            api.ResultRelease(result);
            throw new Exception($"Shader compilation failed for {fileName} (status {status}):\n{err}");
        }

        var length = (int)api.ResultGetLength(result);
        var bytesPtr = api.ResultGetBytes(result);
        var bytes = new byte[length];
        for (var i = 0; i < length; i++)
            bytes[i] = bytesPtr[i];

        api.ResultRelease(result);
        return bytes;
    }

    static void AppendByteArray(StringBuilder sb, string name, byte[] data)
    {
        sb.AppendLine($"    public static readonly byte[] {name} =");
        sb.AppendLine("    [");
        for (var i = 0; i < data.Length; i += 16)
        {
            var chunk = data.AsSpan(i, Math.Min(16, data.Length - i));
            var line = string.Join(", ", chunk.ToArray().Select(b => $"0x{b:X2}"));
            sb.Append("        ");
            sb.Append(line);
            sb.AppendLine(i + chunk.Length < data.Length ? "," : "");
        }
        sb.AppendLine("    ];");
    }

    static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(Directory.GetCurrentDirectory());
        while (dir != null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "Square.slnx")))
                return dir.FullName;
            dir = dir.Parent;
        }
        throw new Exception("Could not locate repository root (Square.slnx).");
    }
}
