<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <Description>Square Extensions: optional components and integrations</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Square\Square.csproj" />
    <ProjectReference Include="..\Square.Compiler\Square.Compiler.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0" />
    <InternalsVisibleTo Include="Square.Platform.Tests" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="**\*.sqv" />
  </ItemGroup>

</Project>
